### ISSUE TITLE
Driver not showing in unraid

### ISSUE THREAD

**Issue by Betanu701** [ich777/unraid-coral-driver#6]
Currently, the newest driver in unraid in 2022.11.14. I see you have several new releases of the driver. Do I need to do something special to pull in the new releases? For instance the one released ~16 days ago 6.1.12 .

**Comment by ich777** [comment]
Please ignore those releases, these are for different Unraid versions which are not publicly available and will only work if you are on this specific Unraid version.

On what Unraid version are you? I would strongly recoomend that you post your Diagnostics because I can’t help with that little information that you’ve provided.

I‘ll close this Issue here, please report that on the support thread.
